### ISSUE TITLE
Haptic feedback not working

### ISSUE THREAD

**Issue by LeonardRockstar** [svtek/SceneKitVideoRecorder#10]
Initializing the recorder with audio disables haptic feedback on iPhone 7 Plus. Apparently this is normal behavior, since the native camera app does the same thing. Is it possible to set up the audio when the recording starts, instead of in the initializer?

**Comment by okaris** [comment]
It is possible but it might cause a delay in the beginning. Audio and video has different sources and intervals. So they one another in the beginning to sync. I can seperate audio setup method and make it publicly accessible and leave it up to the user.

**Comment by okaris** [comment]
Audio setup is now seperate and must be called explicitly to start audio recording.
