### ISSUE TITLE
Video is not being saved / File is empty

### ISSUE THREAD

**Issue by LeonardRockstar** [svtek/SceneKitVideoRecorder#15]
After calling startWriting and finishWriting multiple times in a row, the recorder stops working. A file is created, but it is empty. This happens with the demo project as well as my own.
In the demo project I'm getting the error: `Video /private/var/mobile/Containers/Data/Application/09B7703C-A173-4EB5-BC8E-F482C2ACDAD8/tmp/output.mp4 cannot be saved to the saved photos album: Error Domain=AVFoundationErrorDomain Code=-11800 "The operation could not be completed" UserInfo={NSUnderlyingError=0x1c0445310 {Error Domain=NSOSStatusErrorDomain Code=-12893 "(null)"`

Issue environment:
- Device Model: iPhone 7 Plus
- Xcode Version: Xcode 9 GM
- iOS Version: 11.0 (15A372)
- Pod Version or Repo Commit: 1.3.1

**Comment by LeonardRockstar** [comment]
The error still persists in 1.3.2.

**Comment by notdetninja47** [comment]
This happens on my side as well

**Comment by notdetninja47** [comment]
@LeonardRockstar will this bug occur if we recreate recorder after each recording?

**Comment by notdetninja47** [comment]
On my side, I'm creating Asset from URL I got, but it has 0 tracks

**Comment by LeonardRockstar** [comment]
@notdetninja47 Yes, the bug still occurs if I recreate the recorder.

**Comment by notdetninja47** [comment]
@okaris your opinion that problem is with file url? Not with recording itself?

**Comment by LeonardRockstar** [comment]
If this is of any help, the bug still occurs even if I recreate the recorder with a different file url each time.

**Comment by LeonardRockstar** [comment]
I did some more testing and found that when the error occurs renderSnapshot isn't getting called, since nothing in the frameQueue.async block gets executed.

**Comment by okaris** [comment]
I will push some changes in 2 days which doesn’t directly address this but might fix it

**Comment by LeonardRockstar** [comment]
Seems to be fixed now

**Comment by LeonardRockstar** [comment]
After some more testing I found that, while it is rarer, the error still occurs, where the code inside frameQueue.async stops getting executed.

**Comment by hablema** [comment]
Seems to be fixed in the 1.3.8 update

**Comment by okaris** [comment]
Can you please try with the new version (1.4.0). I am closing this issue for now since other people stopped experiencing this after 1.3.8
