### ISSUE TITLE
Different video bugs on different devices

### ISSUE THREAD

**Issue by notdetninja47** [svtek/SceneKitVideoRecorder#16]
- [+] Issue is reproducible in the Demo Project
- [+] Issue is reproducible with a clean install
- [+] You are running on a Device and not the Simulator
- [+] You have searched existing issues (Open and Closed)
- [+] You are using an appropriate version of XCode and iOS

Runs well on iPhone 6S with iOS 11 beta.

Issue environment:

- Device Model: iPhone 7 plus
- Xcode Version: Xcode 9 GM
- iOS Version: 11 release
- Pod Version or Repo Commit: last version

Issue Details:
The video is corrupted, please have a look at the photo. Bug with incorrect size is also can be seen on iPhone 6S Plus (without color bug), so I think this is a problem of all 5.5 iPhones.

**Comment by notdetninja47** [comment]
![194a1b65-c48e-4edc-8e5b-ebb1acefb589](https://user-images.githubusercontent.com/17043838/30895550-a531925c-a353-11e7-88bc-05fea49059cc.jpg)

**Comment by okaris** [comment]
@notdetninja47 The black frame problem should now be fixed. Please check that. Since i don't have an iPhone7 I can not verify.

The color bug should be history now. It was happening with the old core of the repo. If it can be consistently reproduced please open another issue about that so it is easier to track. 

Thank you.

**Comment by notdetninja47** [comment]
Currently, cannot install your app through CocoaPods. Yesterday had problems with code from your repo, so installed your pod, but now it gives me an error
[!] Unable to find a specification for `SceneKitVideoRecorder`

**Comment by okaris** [comment]
Please run `pod repo update` in the terminal before running `pod install`
Probably your cocoapods repository is old and needs updating to recognise newly added pods

**Comment by notdetninja47** [comment]
But is resolved
