### ISSUE TITLE
pod import error

### ISSUE THREAD

**Issue by hablema** [svtek/SceneKitVideoRecorder#17]
<img width="269" alt="screen shot 2017-09-27 at 1 14 41 pm" src="https://user-images.githubusercontent.com/1577330/30901565-f8f449ac-a385-11e7-9d40-e67756631b02.png">

Just installing from the pod the project gives these errors when building before writing any code. Please tell me how to correct it.

Issue environment:
- Xcode Version: 9

**Comment by okaris** [comment]
Hello @hablema 

This project is not Swift 4 ready yet. Please change your project swift version to swift 3.2.
This option can be found under target build settings.

**Comment by hablema** [comment]
Thanks.
