### ISSUE TITLE
Starting white frame

### ISSUE THREAD

**Issue by hablema** [svtek/SceneKitVideoRecorder#18]
Hi,

The video recording works fine but all the videos have a single transparent frame. How can i avoid that or remove it so that thumbnails shows correct image in all places.

Issue environment:

- Device Model: iPhone 7
- Xcode Version: 9
- iOS Version: 11
- Pod Version or Repo Commit: 1.3.2

Issue Details:

**Comment by okaris** [comment]
1.3.3 fixes this. Please try and let me know.

**Comment by hablema** [comment]
Updated the pod, But now its optional unwrapping error in  `captureSession.stopRunning()` under ' finishWriting ' method. Anything i should have changed.

**Comment by hablema** [comment]
The white frame is still coming in the latest update 1.3.8

**Comment by okaris** [comment]
Can you please try with the new version (1.4.0) This should be fixed now. Promise

**Comment by hablema** [comment]
Awesome. It has been fixed. It works fine now and multiple videos in the same session is also working without any videos being lost. No black/white thumbnails or starting frames. Kudos.

Have an issue with the new audio method. Audio not being recorded. Have started an issue for the same.

**Comment by huntermonk** [comment]
I'm also getting this issue. If I attempt to replay the video using `AVPlayerLooper`, there is a noticeable "flash", where the background is visible because the video is transparent for at least one frame.

This is on version `1.5.1`. iOS `11.2.1`. Xcode 9.2.

**Comment by huntermonk** [comment]
@sahin we spoke briefly on Twitter about this issue. Thanks!
