### ISSUE TITLE
After a new build always crash once on the device

### ISSUE THREAD

**Issue by Francescu** [svtek/SceneKitVideoRecorder#21]
After a new build, it always crash during the first time we try to record, then never crashes again (until we rebuild on Xcode).

# Issue environment:

Notice that we're using ARKit, Xcode 9, Swift 4 and iOS 11.

- Device Model: iPhone 6s (tested on two different devices)
- Xcode Version: 9
- iOS Version: 11

# Issue Details:
In `SceneKitVideoRecorder.swift` line `284` 
```swift
self?.writer.startSession(atSourceTime: (self?.getAppendTime())!)
```

```
2017-10-10 17:36:02.021044+0200 ARText[1935:518028] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVAssetWriter startSessionAtSourceTime:] invalid parameter not satisfying: CMTIME_IS_NUMERIC(startTime)'
*** First throw call stack:
(0x186297d38 0x1857ac528 0x18baff378 0x1009731c4 0x100970db4 0x1015e549c 0x1015e545c 0x1015f4110 0x1015e89a4 0x1015f5104 0x1015fc100 0x185ec2fe0 0x185ec2c30)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by Francescu** [comment]
@okaris: I confirm `f718d9d` fixed the issue

**Comment by okaris** [comment]
Thanks for the input and update
