### ISSUE TITLE
Audio not recorded

### ISSUE THREAD

**Issue by hablema** [svtek/SceneKitVideoRecorder#23]
Issue environment:

- Device Model: iPhone 7
- Xcode Version: 9.2 Beta 2
- iOS Version: 11.1 
- Pod Version or Repo Commit: 1.4.0

Issue Details:

The audio is not being recorded in the new method `recorder?.setupAudio()` . Have tried adding it in the beginning of the controller also in the recordbuttontapped method. Still no audio. The microphone permission was asked first time asked and allowed.

**Comment by LeonardRockstar** [comment]
I'm experiencing the same issue

**Comment by okaris** [comment]
Will quickly look into this. Is this happening when you open your app the second time after giving permissions?

**Comment by LeonardRockstar** [comment]
@okaris Yes, it's still happening after opening the app a second time.

**Comment by hablema** [comment]
The library crashed when recording audio.

`    let aAudioAssetTrack : AVAssetTrack = aAudioAsset.tracks(withMediaType: AVMediaTypeAudio)[0]`


No ready for media data
2017-10-25 10:59:52.949599+0530 CookbookARTK[3121:1288667] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray'
*** First throw call stack:
(0x180f6dd04 0x1801bc528 0x180ec90c4 0x10606d934 0x106082f98 0x105b2f418 0x105b2cbb4 0x105b2b6b4 0x181937b70 0x106c6149c 0x106c6145c 0x106c6d56c 0x106c72b54 0x106c72880 0x180b97120 0x180b96c20)
libc++abi.dylib: terminating with uncaught exception of type NSException


pod version 1.4.1
