### ISSUE TITLE
Adding subviews to recorded video

### ISSUE THREAD

**Issue by hablema** [svtek/SceneKitVideoRecorder#25]
Issue environment:

- Device Model: iPhone 7
- Xcode Version: 9.1
- iOS Version: 11.1
- Pod Version or Repo Commit: 1.4.0

Issue Details:

How can i make an imageview that is a subview of ARSCNView include in the recorded video. Trying to add an image watermark to the saved video.

**Comment by okaris** [comment]
This is not a feature that should be in this library. I can suggest https://github.com/John-Connolly/Merge for applying watermark on top of your recorded videos.

**Comment by hablema** [comment]
Thanks. Did it with Merge.
