### ISSUE TITLE
Audio recording failed

### ISSUE THREAD

**Issue by hablema** [svtek/SceneKitVideoRecorder#27]
The repo crashed when recording audio.

let aAudioAssetTrack : AVAssetTrack = aAudioAsset.tracks(withMediaType: AVMediaTypeAudio)[0]

No ready for media data
2017-10-25 10:59:52.949599+0530 CookbookARTK[3121:1288667] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray'
*** First throw call stack:
(0x180f6dd04 0x1801bc528 0x180ec90c4 0x10606d934 0x106082f98 0x105b2f418 0x105b2cbb4 0x105b2b6b4 0x181937b70 0x106c6149c 0x106c6145c 0x106c6d56c 0x106c72b54 0x106c72880 0x180b97120 0x180b96c20)
libc++abi.dylib: terminating with uncaught exception of type NSException

Issue environment:

- Device Model: iPhone 7
- Xcode Version: 9.1 beta 2
- iOS Version: 11.1 beta 5
- Pod Version or Repo Commit:  1.4.1

Issue Details:

**Comment by okaris** [comment]
This seems like it is caused by lacking audio in the resulting recordings despite audio recording is enabled. Please check that if it is caused by the microphone access permissions are correct and let me know.
