### ISSUE TITLE
 Crash on finishWriting: index 0 beyond bounds for empty NSArray

### ISSUE THREAD

**Issue by Francescu** [svtek/SceneKitVideoRecorder#33]
Issue environment:

- Device Model: iPhone X, iPhone 8 plus
- Xcode Version: 9.1
- iOS Version: 11
- Pod Version or Repo Commit: `dc742c912fac986edb68471ccefdd7b24b928b1a`

Issue Details:

<img width="977" alt="screen shot 2017-11-22 at 14 12 20" src="https://user-images.githubusercontent.com/1433362/33169810-48512442-d046-11e7-97bf-bd4bf79c26c1.png">

<img width="420" alt="screen shot 2017-11-22 at 14 12 14" src="https://user-images.githubusercontent.com/1433362/33169828-56a4e0ec-d046-11e7-801d-bd5403711e39.png">

**Comment by halileohalilei** [comment]
This issue was addressed and fixed in version 1.5.1 @okaris

**Comment by Francescu** [comment]
Nice, I just made PR #34  which add the new commits to the `swift4` branch.

**Comment by okaris** [comment]
Closed by #30
