### ISSUE TITLE
How to handle error if the recording is corrupted?

### ISSUE THREAD

**Issue by lsamaria** [svtek/SceneKitVideoRecorder#59]
Hello, this library works GREAT!!!

When recording or more importantly stopping and saving, how do I handle errors if the video url is somehow messed up?

The current callback in your example Swift file is a `URL`:

```
self.recorder?.finishWriting().onSuccess { [weak self] url in
                
    self?.checkAuthorizationAndPresentActivityController(toShare: url, using: self!)
}
```

Is there  tuple available with a `URL` and `NSERROR`?

```
 self.recorder?.finishWriting().onSuccess { [weak self] (url, error) in

    if let error = error {

         // alert user recording failed
         return
    }

    self?.checkAuthorizationAndPresentActivityController(toShare: url, using: self!)
}
```

Or is the error handling in an entirely different function meaning we call one for success and another for failure?:

```
self.sceneKitVideoRecorder?.finishWriting().onFailure(callback: { [weak self](error) in
                
    print("Recording Failed")
})
```

**Comment by ahmetardal** [comment]
You should be able to do the following:

```
self.recorder?.finishWriting().onSuccess { [weak self] url in
    self?.checkAuthorizationAndPresentActivityController(toShare: url, using: self!)
}.onFailure { error in
    print(error)
}
```

**Comment by lsamaria** [comment]
Thanks, perfect, much appreciated!!!

You did an EXCELLENT job with this library. Much RESPECT to you!

After I launch my app can I list it on your "apps that are using this library" page?

**Comment by ahmetardal** [comment]
Sure, send us a PR when it's launched.

**Comment by lsamaria** [comment]
np, thanks
