### ISSUE TITLE
Recorder Crashing

### ISSUE THREAD

**Issue by LeonardRockstar** [svtek/SceneKitVideoRecorder#6]
<img width="1180" alt="bildschirmfoto 2017-09-08 um 15 37 04" src="https://user-images.githubusercontent.com/30780859/30214135-9e0c98fc-94ab-11e7-9faa-c62956441431.png">
<img width="535" alt="bildschirmfoto 2017-09-08 um 15 32 13" src="https://user-images.githubusercontent.com/30780859/30214136-9e1b54f0-94ab-11e7-9de5-0a31de8a00bf.png">

**Comment by okaris** [comment]
You need to call recorder.prepare() after scene view appears and before starting recording.
