### ISSUE TITLE
How to check if recorder is recording?

### ISSUE THREAD

**Issue by lsamaria** [svtek/SceneKitVideoRecorder#60]
How can I check if the recorder is recording? For eg.

```
if recorder?.isWriting {

    _ = recorder?.startWriting()

} else {

    recorder?.finishWriting().onSuccess { [weak self] url in

        print("recording success", url)
                
    }.onFailure(callback: { (error) in

        print("recording failed", error)
    })
}
```

**Comment by ahmetardal** [comment]
You can inspect this file to understand what you can do with this component:

https://github.com/svhawks/SceneKitVideoRecorder/blob/master/SceneKitVideoRecorder/Classes/SceneKitVideoRecorder.swift

You can use a boolean property for `isRecording`. Set it when you start recording.

**Comment by lsamaria** [comment]
Im using a boolean now, thanks for the help :)
