### ISSUE TITLE
Chromakeyed video recording cause white background

### ISSUE THREAD

**Issue by ozgurshn** [svtek/SceneKitVideoRecorder#62]
Issue environment:

- Device Model: iPhone mini running iOS 15
- Xcode Version: Xcode 13
- iOS Version: iOS 15
- Pod Version or Repo Commit:

Issue Details:
I record the scene where I play a video ver a SCNPlane in which I remove green background of video using surface shader. This cause recorded video to have a white background instead of transparent one. Any ideas?
![IMG_5889](https://user-images.githubusercontent.com/2404074/138481568-a547af18-e6a6-471b-b898-a38a3ace50d4.PNG)

![IMG_5887](https://user-images.githubusercontent.com/2404074/138481533-68aef6a1-3b20-45dd-ae04-fcca64061285.PNG)

**Comment by ahmetardal** [comment]
@ozgurshn

Hi Özgür,

Thanks for your interest in `SceneKitVideoRecorder`.
Unfortunately this repo is not being actively maintained for a long time.
I hope you find a solution to your problem.

**Comment by ozgurshn** [comment]
Thanks for good wishes & letting me know @ardalahmet. I solved it using SKEffectNode.

**Comment by ahmetardal** [comment]
@ozgurshn 

Great, happy to hear that.
